apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-full-output
  namespace: vm-cbt-demo
spec:
  storageClassName: cbt-demo-hpp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: backup.kubevirt.io/v1alpha1
kind: VirtualMachineBackupTracker
metadata:
  name: hello-tracker
  namespace: vm-cbt-demo
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-cbt-demo
---
apiVersion: backup.kubevirt.io/v1alpha1
kind: VirtualMachineBackup
metadata:
  name: hello-full
  namespace: vm-cbt-demo
spec:
  source:
    apiGroup: backup.kubevirt.io
    kind: VirtualMachineBackupTracker
    name: hello-tracker
  pvcName: hello-full-output
