apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-incremental-output
  namespace: vm-cbt-demo
spec:
  storageClassName: cbt-demo-hpp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: backup.kubevirt.io/v1alpha1
kind: VirtualMachineBackup
metadata:
  name: hello-incremental
  namespace: vm-cbt-demo
spec:
  source:
    apiGroup: backup.kubevirt.io
    kind: VirtualMachineBackupTracker
    name: hello-tracker
  pvcName: hello-incremental-output
